package com.example.shiftv1.schedule;

import com.example.shiftv1.breaks.BreakPeriod;

import java.time.LocalDate;
import java.time.LocalTime;

import java.time.temporal.ChronoUnit;
import java.util.List;
import java.util.stream.Collectors;

public record ScheduleGridAssignmentDto(
        Long id,
        Long employeeId,
        String employeeName,
        LocalDate workDate,
        String shiftName,
        LocalTime startTime,
        LocalTime endTime,
        LocalTime breakStart,
        LocalTime breakEnd,
        Integer breakMinutes,
        List<BreakDto> breaks,
        Boolean isFree,
        Boolean isOff,
        Boolean isLeave) {

    public static ScheduleGridAssignmentDto from(ShiftAssignment assignment, List<BreakPeriod> breakPeriods) {
        LocalTime breakStart = null;
        LocalTime breakEnd = null;
        Integer breakMinutes = null;
        if (breakPeriods != null && !breakPeriods.isEmpty()) {
            BreakPeriod lunch = breakPeriods.stream()
                    .filter(bp -> bp.getType() == BreakPeriod.BreakType.LUNCH)
                    .findFirst()
                    .orElse(null);
            if (lunch != null) {
                breakStart = lunch.getStartTime();
                breakEnd = lunch.getEndTime();
                if (breakStart != null && breakEnd != null) {
                    breakMinutes = (int) ChronoUnit.MINUTES.between(breakStart, breakEnd);
                }
            }
        }
        List<BreakDto> breakDtos = breakPeriods == null ? List.of()
                : breakPeriods.stream()
                .map(bp -> new BreakDto(
                        bp.getId(),
                        bp.getType(),
                        bp.getStartTime(),
                        bp.getEndTime(),
                        bp.getAutoGenerated() != null && bp.getAutoGenerated()))
                .collect(Collectors.toList());
        return new ScheduleGridAssignmentDto(
                assignment.getId(),
                assignment.getEmployee() != null ? assignment.getEmployee().getId() : null,
                assignment.getEmployee() != null ? assignment.getEmployee().getName() : null,
                assignment.getWorkDate(),
                assignment.getShiftName(),
                assignment.getStartTime(),
                assignment.getEndTime(),
                breakStart,
                breakEnd,
                breakMinutes,
                breakDtos,
                normalizeFlag(assignment.getIsFree()),
                normalizeFlag(assignment.getIsOff()),
                normalizeFlag(assignment.getIsLeave())
        );
    }

    private static Boolean normalizeFlag(Boolean flag) {
        return flag != null && flag;
    }
    public record BreakDto(Long id,
                           BreakPeriod.BreakType type,
                           LocalTime start,
                           LocalTime end,
                           Boolean autoGenerated) {
    }
}
